export const ROUTE = {
  home: '/',
  signin: '/signin',
  signup: '/signup',
  notFound: '/not-found',
  verify: '/user/verify',
  verifyWithQueryParam: '/user/verify?token=',
  dashboard: '/user/dashboard',
  userSignup: '/user/signup',
  userLogin: '/user/login',
  userLogout: '/user/logout',
  myProfile: '/user/myprofile',
  createGroup: '/create-group',
  createPokerboard: '/create-pokerboard',
  importTicket: '/pokerboard/:id/import-tickets',
  pokerboard: '/pokerboard/:id',
  acceptInvite: '/poker-board/invite',
  acceptInviteWithQueryParam: '/poker-board/verify?pokerBoardId=',
  groupPage: '/groups',
  tickets: '/tickets',
  report: '/report',
};
