export const TEXT = {
  alreadyHaveAnAccout: "Already have an account? Sign in",
  bearer: "Bearer ",
  cardsEstimated: "Cards Estimated",
  createGroup: "Create Group",
  createPokerboard: "Create Pokerboard",
  dashboard: "Dashboard",
  deckType: "Deck Type",
  doNotHaveAnAccount: "Do not have an account? Sign up",
  email: "Email",
  emailVerificationLinkValidity:
    "Email verification link will be valid till next 6 hours",
  even: "EVEN",
  fibonacci: "FIBONACCI",
  groups: "Groups",
  logout: "Logout",
  name: "Name",
  odd: "ODD",
  pageNotFound: "404 Page Not Found",
  planPoker: "Plan Poker",
  profile: "Profile",
  reSendEmail: "Re-Send Email",
  pokerboards: "Pokerboards",
  sendEmailVerificationLink: "Send Email Verification Link",
  serial: "SERIAL",
  signin: "Sign In",
  signup: "Sign Up",
  tickets: "Tickets",
  username: "Username",
  viewDetails: "View Details",
  pleaseCreateAGroup:
    "You are not a member of any group. " +
    "Please create a group or ask the admin of the group to send you an invite",
  pleaseCreateAPokerboard:
    "You are not a part of any pokerboard. " +
    "Please create a pokerboard or ask the manager of the pokerboard to send you an invite",
  goToCreateGroup: "Go to Create Group",
  goToCreatePokerboard: "Go to Create Pokerboard",
  goToHome: "Go to Home",
  goToPokerboard: "Board",
  import: "Import",
  save: "Save",
  select: "Select",
  remove: "Remove",
  next: "Next",
  prev: "Prev",
  accessDenied: "Access Denied",
}
